# Generated by Django 4.0.6 on 2023-01-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='published_country',
            new_name='published_countries',
        ),
    ]
