# Generated by Django 4.0.6 on 2023-01-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_rename_published_country_author_published_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_countries',
        ),
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
